//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chitieu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class expenditure
    {
        public int id { get; set; }
        public System.DateTime datetime { get; set; }
        public int amount { get; set; }
        public string note { get; set; }
    }
}
